### ISSUE TITLE
IndexError in evaluation/predict.py (classifier.py)

### ISSUE THREAD

**Issue by sgagnon-tootelo** [twerkmeister/iLID#5]
Hello twerkmeister, sorry if is trivial, is my first experience with caffe, I succede to preprocessing the audios, trained it with Berlin_net model, but at the evaluation step I get:

Traceback (most recent call last):
  File "predict.py", line 47, in <module>
    predict(args.input, args.proto, args.model, args.output)
  File "predict.py", line 20, in predict
    raw_scale=255 # convert 0..255 values into range 0..1
  File "/home/sylvain/caffe/python/caffe/classifier.py", line 29, in __init__
    in_ = self.inputs[0]
IndexError: list index out of range

I put the complete log in attachment... If someone can help me. Thanks
[output.log](https://github.com/twerkmeister/iLID/files/1834670/output.log)

**Comment by deibraz-free** [comment]
Still no response, ehh?
